"""
candidates.py — Experiment 10: finite-candidate interventional search.

CONTEXT (see experiments/10-interventional-search.md, the pre-registration).
Experiment 9 exhausted correlational proposal mining; the acceptance rule
is the only causally-grounded component. Here SELECTION becomes
interventional: each round a 12-candidate pool is generated by cheap,
deliberately fallible sources (the exp-9 miners among them), every
candidate is actually patched (jointly with the accepted basis) and ranked
by measured closure gain on the discovery pairs, and the unchanged
acceptance rule takes the best candidate iff its gain >= eps_gain.

Uniform patch convention (the coordinate-luck control): candidates are
unit directions in the WORKING coordinates of the regime (x benign, z
adversarial), orthogonalized against the accepted basis; the patch is the
plain orthogonal-coordinate swap in working coordinates, pulled back to
stream space before touching the model. Success is judged after pullback.
This gives exp-9's whitened-miner directions the fair interventional test
their oblique whitened-swap patch denied them.

Registered diagnostics that adjudicate the trichotomy (selection works /
support-or-patch failure / mere reranking): per-round per-candidate tables
of source, measured gain, and pulled-back angle to the causal plane; source
attribution of every accepted direction.

Gradient-based proposal generation is DEFERRED to Experiment 11 by design
(per review): it is a different machine and does not appear here.

Run: python3 candidates.py --outdir out/mess3-L4
`--selftest` runs the standard four machinery checks and exits.
"""

import argparse
import json
import os

import numpy as np
import torch
import torch.nn.functional as F

from abstraction import center_by_position, kl_rows
from adversarial import ZView
from discover import (PairSet, mined_direction, principal_angles_deg,
                      self_checks)
from midstream import kl_by_horizon, orthonormal, stream_to
from miners import patch_rowspace, sqrt_and_inv
from model import GPT, GPTConfig
from processes import PROCESSES

LAYER = 1

REGISTERED = {"kappa": 100.0, "k_max": 8, "eps_gain": 0.05,
              "eps_drop": 0.01, "pairs_disc": 400, "pairs_eval": 600,
              "basis_seqs": 800, "m": 3}


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default="out/mess3-L4")
    ap.add_argument("--kappa", type=float, default=REGISTERED["kappa"])
    ap.add_argument("--k-max", type=int, default=REGISTERED["k_max"])
    ap.add_argument("--eps-gain", type=float, default=REGISTERED["eps_gain"])
    ap.add_argument("--eps-drop", type=float, default=REGISTERED["eps_drop"])
    ap.add_argument("--pairs-disc", type=int,
                    default=REGISTERED["pairs_disc"])
    ap.add_argument("--pairs-eval", type=int,
                    default=REGISTERED["pairs_eval"])
    ap.add_argument("--basis-seqs", type=int,
                    default=REGISTERED["basis_seqs"])
    ap.add_argument("--m", type=int, default=REGISTERED["m"])
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--force-invalid", action="store_true")
    args = ap.parse_args(argv)

    with open(os.path.join(args.outdir, "config.json")) as f:
        cfg = json.load(f)
    proc = PROCESSES[cfg["process"]]()
    registered_cfg = (proc.name == "mess3" and cfg["layers"] == 4
                      and cfg["seq_len"] == 32 and cfg["d_model"] == 64
                      and cfg["burn_in"] == 4)
    if not registered_cfg and not args.selftest and not args.force_invalid:
        print("Experiment 10 is registered for the Experiment-6/8/9 setting "
              "(mess3 / 4 layers / d_model 64 / seq_len 32 / burn_in 4); "
              f"this config is {cfg['process']} L{cfg['layers']} "
              f"d{cfg['d_model']} T{cfg['seq_len']} b{cfg['burn_in']}. "
              "Use --selftest or --force-invalid.")
        return
    overridden = [k for k, v in REGISTERED.items() if getattr(args, k) != v]
    if overridden and not args.selftest and not args.force_invalid:
        print(f"Experiment 10 parameters are registered; overridden: "
              f"{overridden}. Use --force-invalid for an exploratory run.")
        return
    if overridden:
        print(f"NOTE: EXPLORATORY RUN — non-registered parameters "
              f"{overridden}; verdicts below are NOT Experiment 10.\n")
    if args.seed != 0 and not args.selftest and not args.force_invalid:
        print(f"Experiment 10 registers seed 0 (T's anchor depends on it); "
              f"got {args.seed}. Use --force-invalid.")
        return
    if args.seed != 0:
        print(f"NOTE: EXPLORATORY RUN — seed {args.seed} != 0.\n")

    L, burn, V, m = cfg["seq_len"], cfg["burn_in"], proc.V, args.m
    d = cfg["d_model"]
    model = GPT(GPTConfig(vocab=V, seq_len=L, d_model=d,
                          n_layers=cfg["layers"]))
    model.load_state_dict(torch.load(os.path.join(args.outdir, "model.pt"),
                                     map_location="cpu"))
    model.eval()

    # ----- validity gate (P6, enforced) ---------------------------------------
    Xg = proc.sample(2000, L, np.random.default_rng(args.seed + 999))
    with torch.no_grad():
        tot, cnt = 0.0, 0
        for i in range(0, len(Xg), 256):
            logits = model(torch.from_numpy(Xg[i:i + 256]))
            tgt = torch.from_numpy(Xg[i:i + 256, 1:]).reshape(-1)
            tot += F.cross_entropy(logits[:, :-1].reshape(-1, V), tgt,
                                   reduction="sum").item()
            cnt += tgt.numel()
    gap_opt = tot / cnt - cfg["optimal_nll"]
    p6 = gap_opt <= 0.005
    print(f"validity gate: gap-to-optimal {gap_opt:+.4f} nats — "
          f"{'PASS' if p6 else 'FAIL'}\n")
    if not p6 and not args.selftest and not args.force_invalid:
        print("exiting: validity gate failed.")
        return

    disc = PairSet(model, proc, cfg, args.pairs_disc, m, args.seed + 111, 800,
                   layer=LAYER)
    ev = PairSet(model, proc, cfg, args.pairs_eval, m, args.seed + 777, 800,
                 layer=LAYER)
    self_checks(model, ev, LAYER, m, V)
    if args.selftest:
        return

    print(f"=== Experiment 10: interventional candidate search | {proc.name}"
          f" | patch L{LAYER} | kappa = {args.kappa:g} | 12-candidate pool "
          "per round ===\n")

    # ----- observable refs -----------------------------------------------------
    q_src_d = disc.run(model, None, src_side=True)
    q_un_d = disc.run(model, None)
    q_full_d = disc.run(model, np.eye(d))
    D0 = float(kl_rows(q_src_d, q_un_d).mean())
    Dfull = float(kl_rows(q_src_d, q_full_d).mean())
    assert D0 > Dfull
    c_obs = lambda q: (D0 - float(kl_rows(q_src_d, q).mean())) / (D0 - Dfull)
    assert abs(c_obs(q_full_d) - 1.0) < 1e-12

    # ----- anchor: the frozen exp-6 covariance loop ---------------------------
    print("[anchor] frozen Experiment-6 loop:")
    Q = np.zeros((d, 0))
    q_cur, c_cur = q_un_d, 0.0
    while Q.shape[1] < args.k_max:
        v = mined_direction(disc, Q, kl_rows(q_src_d, q_cur))
        Q_try = np.hstack([Q, v[:, None]])
        q_try = disc.run(model, Q_try @ Q_try.T)
        if c_obs(q_try) - c_cur < args.eps_gain:
            break
        Q, q_cur, c_cur = Q_try, q_try, c_obs(q_try)
        print(f"  k={Q.shape[1]}: c_obs {c_cur:.1%}")
    Qc = Q
    assert Qc.shape[1] == 2 and abs(c_cur - 0.998) < 0.005, \
        "failed to reproduce Experiment 6's fixed point"
    Pc = Qc @ Qc.T
    print(f"[anchor] reproduced: k* = 2, c_obs = {c_cur:.1%}\n")

    # ----- T and whitening -----------------------------------------------------
    kap = args.kappa
    rng0 = np.random.default_rng(0)
    Gj = rng0.standard_normal((d, 2))
    Gj -= Qc @ (Qc.T @ Gj)
    Qj = orthonormal(Gj)
    T = np.eye(d) - (1 - 1 / kap) * Pc + (kap - 1) * (Qj @ Qj.T)
    Tinv = np.eye(d) + (kap - 1) * Pc + (1 / kap - 1) * (Qj @ Qj.T)
    assert np.allclose(T @ Tinv, np.eye(d), atol=1e-9)
    assert np.allclose(T @ (orthonormal(T @ Qc) @ orthonormal(T @ Qc).T)
                       @ Tinv, Pc, atol=1e-9)
    print("transform checks passed\n")

    rng_b = np.random.default_rng(args.seed + 555)
    Xb = proc.sample(args.basis_seqs, L, rng_b)
    Sb = stream_to(model, torch.from_numpy(Xb), LAYER).double().numpy()
    keep = np.arange(burn, L - 1)
    Rb = center_by_position(Sb[:, keep].reshape(-1, d), np.tile(keep, len(Xb)),
                            np.ones(len(Xb) * len(keep), dtype=bool))
    Sig_x = np.cov(Rb.T)
    Sig_z = T @ Sig_x @ T

    class Regime:
        def __init__(self, name, view_raw, view_wht, S, Sinv, pull, back):
            self.name, self.view_raw, self.view_wht = name, view_raw, view_wht
            self.S, self.Sinv, self.pull, self.back = S, Sinv, pull, back

    Sx, Sx_inv = sqrt_and_inv(Sig_x)
    Sz, Sz_inv = sqrt_and_inv(Sig_z)
    regimes = {
        "ben": Regime("ben", disc, ZView(disc, Sx_inv), Sx, Sx_inv,
                      lambda P: P, lambda v: v),
        "adv": Regime("adv", ZView(disc, T), ZView(disc, T @ Sz_inv),
                      Sz, Sz_inv, lambda P: T @ P @ Tinv,
                      lambda v: Tinv @ v),     # working dir -> stream dir
    }

    def candidate_pool(rg, B, weights, rnd):
        """12 registered candidates as (source, unit working-space dir)."""
        rng = np.random.default_rng(args.seed + 1000 + rnd)
        ones = np.ones_like(weights)
        cands = [("M1", mined_direction(rg.view_raw, B, weights)),
                 ("M3", mined_direction(rg.view_raw, B,
                                        weights - weights.mean()))]
        Bw = orthonormal(rg.Sinv @ B) if B.shape[1] else np.zeros((d, 0))
        u2 = mined_direction(rg.view_wht, Bw, weights)
        cands += [("M2*S", rg.S @ u2), ("M2*Sinv", rg.Sinv @ u2)]
        p1 = mined_direction(rg.view_raw, B, ones)
        cands.append(("dPCA1", p1))
        cands.append(("dPCA2", mined_direction(
            rg.view_raw, orthonormal(np.hstack([B, p1[:, None]])), ones)))
        for i in range(2):
            cands.append(("rand", rng.standard_normal(d)))
        for i in range(2):
            cands.append(("randS", rg.S @ rng.standard_normal(d)))
        for i in range(2):
            cands.append(("randSinv", rg.Sinv @ rng.standard_normal(d)))
        out = []
        for src, v in cands:
            if B.shape[1]:
                v = v - B @ (B.T @ v)
            n = np.linalg.norm(v)
            if n > 1e-8:
                out.append((src, v / n))
        return out

    def search(rg):
        """Interventional selection with the frozen acceptance rule."""
        B = np.zeros((d, 0))
        q_cur, c_cur = q_un_d, 0.0
        sources, converged = [], False
        rnd = 0
        while B.shape[1] < args.k_max:
            rnd += 1
            w = kl_rows(q_src_d, q_cur)
            print(f"  [{rg.name}] round {rnd} (current c_obs {c_cur:.1%}):")
            best = None
            for src, v in candidate_pool(rg, B, w, rnd):
                assert abs(np.linalg.norm(v) - 1) < 1e-9 and (
                    B.shape[1] == 0 or np.abs(B.T @ v).max() < 1e-8)
                B_try = np.hstack([B, v[:, None]])
                q_try = disc.run(model, rg.pull(B_try @ B_try.T))
                gain = c_obs(q_try) - c_cur
                sv = rg.back(v)
                ang = principal_angles_deg(
                    (sv / np.linalg.norm(sv))[:, None], Qc)[0]
                print(f"      {src:>9}: gain {gain:+6.1%}, pulled-back angle "
                      f"to plane {ang:5.1f} deg")
                if best is None or gain > best[0]:
                    best = (gain, src, v, q_try)
            gain, src, v, q_try = best
            if gain < args.eps_gain:
                print(f"  [{rg.name}] best gain {gain:+.1%} < eps_gain -> "
                      "STOP")
                converged = True
                break
            B = np.hstack([B, v[:, None]])
            q_cur, c_cur = q_try, c_cur + gain
            sources.append(src)
            print(f"  [{rg.name}] accept {src} -> k = {B.shape[1]}, "
                  f"c_obs {c_cur:.1%}")
        if not converged:
            print(f"  [{rg.name}] k_max reached: NON-CONVERGENT")
        changed = True
        while changed and B.shape[1] > 1:
            changed = False
            for j in range(B.shape[1]):
                Bj = np.delete(B, j, axis=1)
                cj = c_obs(disc.run(model, rg.pull(Bj @ Bj.T)))
                if c_cur - cj < args.eps_drop:
                    print(f"  [{rg.name}] coarsen: dropped direction {j + 1} "
                          f"(source {sources[j]})")
                    B, c_cur, changed = Bj, cj, True
                    sources.pop(j)
                    break
        print(f"  [{rg.name}] fixed point: k* = {B.shape[1]}, c_obs = "
              f"{c_cur:.1%}, sources = {sources}\n")
        return B, c_cur, sources, converged

    results = {}
    for rname in ("ben", "adv"):
        print(f"[search/{rname}]:")
        results[rname] = search(regimes[rname])

    # ----- evaluation (exact targets, disjoint pairs) ---------------------------
    q0_e = ev.run(model, None)
    rows_fe = kl_by_horizon(q0_e, ev.p_tgt3, V, m)
    rows_ge = kl_by_horizon(q0_e, ev.p_src3, V, m)
    floor_e = {mm: float(rows_fe[mm].mean()) for mm in rows_fe}
    gap_e = {mm: float(rows_ge[mm].mean()) for mm in rows_ge}
    ms = list(range(1, m + 1))

    def true_closure(P):
        rows_t = kl_by_horizon(ev.run(model, P), ev.p_src3, V, m)
        cl = {mm: (gap_e[mm] - float(rows_t[mm].mean()))
              / (gap_e[mm] - floor_e[mm]) for mm in ms}
        bp = {t: (float(rows_ge[m][idx].mean())
                  - float(rows_t[m][idx].mean()))
              / (float(rows_ge[m][idx].mean())
                 - float(rows_fe[m][idx].mean()))
              for t, idx in ev.groups}
        return cl, bp

    print("evaluation (exact targets; pooled m=1..3 | per-position at m=3):")
    cl_full, bp = true_closure(np.eye(d))
    print(f"  {'full':>6} (k=64)  "
          + "  ".join(f"m={mm}: {cl_full[mm]:>6.1%}" for mm in ms)
          + "   | " + "  ".join(f"t={t}: {bp[t]:.1%}" for t, _ in ev.groups))
    closures, plane_ang = {}, {}
    for rname, (B, c, srcs, conv) in results.items():
        if B.shape[1] == 0:
            closures[rname] = {mm: 0.0 for mm in ms}
            print(f"  {rname:>6} (k=0)   closure 0 by definition")
            continue
        P = regimes[rname].pull(B @ B.T)
        cl, bp = true_closure(P)
        closures[rname] = cl
        sub = patch_rowspace(P, B.shape[1])
        ang = principal_angles_deg(Qc, sub)       # plane WITHIN discovered
        pd = float(np.linalg.norm(sub @ sub.T - Pc))
        plane_ang[rname] = ang
        print(f"  {rname:>6} (k={B.shape[1]})  "
              + "  ".join(f"m={mm}: {cl[mm]:>6.1%}" for mm in ms)
              + "   | " + "  ".join(f"t={t}: {bp[t]:.1%}"
                                    for t, _ in ev.groups)
              + f"   | plane-in-disc angles "
              + "/".join(f"{a:.1f}" for a in ang)
              + f" deg, proj-dist {pd:.3f}")

    # ----- verdicts -------------------------------------------------------------
    print("\nverdicts:")
    print(f"  P1 anchor + transform checks: HOLDS (asserted above)")
    Bb, cb, sb, convb = results["ben"]
    p2 = convb and 0 < Bb.shape[1] <= 4 and \
        closures["ben"][m] >= 0.90 * cl_full[m]
    print(f"  P2 benign (k* <= 4, >= 90% of full): k*={Bb.shape[1]}, "
          f"{closures['ben'][m]:.1%} vs full {cl_full[m]:.1%} — "
          f"{'HOLDS' if p2 else 'FAILS'}")
    Ba, ca, sa, conva = results["adv"]
    p3 = conva and 0 < Ba.shape[1] <= 4 and \
        closures["adv"][m] >= 0.90 * cl_full[m]
    print(f"  P3 adversarial (k* <= 4, >= 90% of full, after pullback): "
          f"k*={Ba.shape[1]}, {closures['adv'][m]:.1%} — "
          f"{'HOLDS' if p3 else 'FAILS'}")
    if Ba.shape[1] == 0:
        p4 = False
        print("  P4 observable/exact on adversarial: NOT TESTED — no "
              "accepted patch")
    else:
        p4 = abs(ca - closures["adv"][m]) <= 0.10
        print(f"  P4 observable/exact on adversarial (accepted k*="
              f"{Ba.shape[1]}): c_obs {ca:.1%} vs exact "
              f"{closures['adv'][m]:.1%} — {'HOLDS' if p4 else 'FAILS'}")
    if "adv" in plane_ang:
        p5 = max(plane_ang["adv"]) <= 15.0
        print(f"  P5 plane containment (both plane dirs within 15 deg of "
              f"discovered): max {max(plane_ang['adv']):.1f} deg — "
              f"{'HOLDS' if p5 else 'FAILS'}")
    else:
        p5 = False
        print("  P5 plane containment: NOT TESTED — no accepted adversarial "
              "subspace")
    print(f"  P6 validity gate: {'HOLDS' if p6 else 'FAILS'}")
    print(f"\nsource attribution: benign {sb}; adversarial {sa}")

    # ----- plot -----------------------------------------------------------------
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        fig, ax = plt.subplots(figsize=(6, 4))
        names = ["full"] + list(results)
        vals = [cl_full[m]] + [closures[r][m] for r in results]
        ax.bar(range(len(names)), vals)
        ax.axhline(0.9 * cl_full[m], ls="--", c="r", label="90% of full")
        ax.set_xticks(range(len(names)))
        ax.set_xticklabels([f"{n}\nk={64 if n == 'full' else results[n][0].shape[1]}"
                            for n in names], fontsize=8)
        ax.set_ylabel(f"exact closure, pooled m={m}")
        ax.set_title(f"{proc.name}: interventional candidate search "
                     f"(kappa={args.kappa:g})")
        ax.legend(fontsize=8)
        p = os.path.join(args.outdir, "experiment10.png")
        fig.tight_layout(); fig.savefig(p, dpi=160); plt.close(fig)
        print(f"\nwrote {p}")
    except Exception as e:
        print(f"\n(plotting skipped: {e})")


if __name__ == "__main__":
    main()
